#include "hal_data.h"



FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    /*
    Workflow summary (all in E² studio)
    1. Create project from FSP USB CDC template
    2. Add your C code in src/
    3. Configure peripherals in FSP GUI (ADC/DAC/GPIO)
    4. Build Project → .elf created
    5. Debug / run → IDE flashes .elf, you can step through code
    6. (Optional) Generate .hex → use Flash Programmer

    Example folder structure after build

    Project/
    ├── Debug/
    │   ├── cdc_demo.elf     ← debug executable
    │   ├── cdc_demo.hex     ← flashable HEX
    │   ├── objects/         ← compiled .o files
    │   └── map/             ← linker map


    Typical workflow

    Debug:
      Build → cdc_demo.elf → Flash → Debug → Step / Inspect → Iterate

    Release:
      Build → cdc_demo.hex → Flash → Run standalone

    Do not flash the ELF directly on standalone devices without debugger; use HEX.

    */

/*----------------------------------------------------------------*/

    //  BEGIN Mirko : UART Code
    fsp_err_t err_uart;

    /* Open UART driver */
    err_uart = R_SCI_B_UART_Open(&g_uart0_ctrl, &g_uart0_cfg);

    if (FSP_SUCCESS != err_uart)
    {
        while(1)
        {
            /* UART init failed */
        }
    }

    /* Send startup message */
    char msg[] = "Hello UART\r\n";

    R_SCI_B_UART_Write(&g_uart0_ctrl,
                     (uint8_t *)msg,
                     strlen(msg));

/*----------------------------------------------------------------*/

/*

    //  BEGIN Mirko : I2C Code
    fsp_err_t err_i2c;

     Open I2C driver
    err_i2c = R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);

    if (FSP_SUCCESS != err_i2c)
    {
        while(1); // error
    }

     Example: send 1 byte to device address 0x50
    uint8_t data = 0x55;
    uint8_t slave_address = 0x50;  // change to your device

*/


       while (1)
       {

           // UART TX :
           R_SCI_B_UART_Write(&g_uart0_ctrl, (uint8_t*)msg, strlen(msg));

/*
           // I2C TX :
            err_i2c = R_IIC_MASTER_SlaveAddressSet(&g_i2c_master0_ctrl,
                                              slave_address,
                                              I2C_MASTER_ADDR_MODE_7BIT);

           // I2C Tx :
           if (FSP_SUCCESS != err_i2c)
           {
               while(1); // error
           }

           err_i2c = R_IIC_MASTER_Write(&g_i2c_master0_ctrl,
                                   &data,
                                   1,
                                   false);   // false = send STOP

           if (FSP_SUCCESS != err_i2c)
           {
               while(1); // error
           }

*/
           // DELAY :

           /* small delay */
           R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);


       }

// END Mirko


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
